// ============================================
// Cryptarena — Full Character Roster (13 Bots)
// ============================================

import { Character } from "@/types";

export const CHARACTERS: Character[] = [
  // ---- Scalper ----
  // ── B-Rank: Regional Champions ──
  {
    id: "saki",
    name: "Saki",
    nameJa: "サキ",
    philosophy: "The calm mind sees the deepest pattern. Wait. Strike. Vanish.",
    tradingStyle: "mean_reversion",
    visualMotif: "White crystal android commander with flowing data streams",
    primaryColor: "#00d4ff",
    secondaryColor: "#0a2a4a",
    emissiveColor: "#0088cc",
    weapon: "Probability Matrix Shield",
    mythReference: "Athena — goddess of strategic warfare",
    personality: "Serene commander who calculates all outcomes before acting",
    battleCry: "すべては計算の内",
    region: "Tokyo",
    rank: "B",
    archetype: "commander",
    stats: { attack: 55, defense: 80, speed: 40, precision: 90, adaptability: 70 },
    ability: {
      name: "Equilibrium Matrix",
      nameJa: "均衡行列",
      description: "Creates a probability shield that reduces drawdown by 50% for 3 ticks",
      triggerCondition: "low_health",
      effect: { type: "drawdown_shield", magnitude: 0.5, durationTicks: 3 },
      cooldownTicks: 8,
    },
  },
  {
    id: "raiko",
    name: "Raiko",
    nameJa: "雷狐",
    philosophy: "Speed is truth. The market rewards the fastest.",
    tradingStyle: "scalper",
    visualMotif: "Lightning fox android with crackling electric circuits",
    primaryColor: "#00ff88",
    secondaryColor: "#0a3a1a",
    emissiveColor: "#00cc66",
    weapon: "Nanosecond Pulse Blades",
    mythReference: "Raijin — god of thunder and lightning",
    personality: "Hyperactive speed demon who executes thousands of micro-trades",
    battleCry: "光より速く",
    region: "Osaka",
    rank: "B",
    archetype: "assassin",
    stats: { attack: 70, defense: 35, speed: 95, precision: 60, adaptability: 55 },
    ability: {
      name: "Afterimage Blitz",
      nameJa: "残像閃撃",
      description: "Doubles trade frequency and PnL for 2 ticks",
      triggerCondition: "winning_streak",
      effect: { type: "pnl_boost", magnitude: 2.0, durationTicks: 2 },
      cooldownTicks: 10,
    },
  },

  // ---- Momentum ----
  {
    id: "musashi",
    name: "Musashi",
    nameJa: "ムサシ",
    philosophy: "Once the blade is drawn, there is no retreat. Commit fully.",
    tradingStyle: "momentum",
    visualMotif: "Samurai robot with heavy golden armor and twin katanas",
    primaryColor: "#ffd700",
    secondaryColor: "#3a2a0a",
    emissiveColor: "#cc9900",
    weapon: "Twin Trend Katanas — 二刀流",
    mythReference: "Miyamoto Musashi — undefeated swordsman",
    personality: "Stoic warrior who never exits a position once entered",
    battleCry: "退かぬ、媚びぬ、省みぬ",
    region: "Kyoto",
    rank: "B",
    archetype: "berserker",
    stats: { attack: 90, defense: 50, speed: 45, precision: 65, adaptability: 40 },
    ability: {
      name: "Iron Stance",
      nameJa: "鉄の構え",
      description: "Doubles position size and locks direction for 3 ticks — all-in commitment",
      triggerCondition: "high_stage",
      effect: { type: "position_scale", magnitude: 2.0, durationTicks: 3 },
      cooldownTicks: 12,
    },
  },
  {
    id: "malik",
    name: "Malik",
    nameJa: "マリク",
    philosophy: "Capital is power. Overwhelm with resources.",
    tradingStyle: "momentum",
    visualMotif: "Ornate golden dragon android with digital coin cape",
    primaryColor: "#ffa500",
    secondaryColor: "#3a2500",
    emissiveColor: "#cc8400",
    weapon: "Infinite Capital Gauntlets",
    mythReference: "Midas — golden touch",
    personality: "Regal titan who crushes opponents through sheer financial mass",
    battleCry: "金は力なり",
    region: "Dubai",
    rank: "B",
    archetype: "titan",
    stats: { attack: 85, defense: 65, speed: 30, precision: 50, adaptability: 45 },
    ability: {
      name: "Capital Surge",
      nameJa: "資本津波",
      description: "Triples position size for 2 ticks — overwhelming capital deployment",
      triggerCondition: "high_stage",
      effect: { type: "position_scale", magnitude: 3.0, durationTicks: 2 },
      cooldownTicks: 15,
    },
  },
  {
    id: "vector",
    name: "Vector",
    nameJa: "ベクトル",
    philosophy: "Data is the only truth. Sentiment is noise.",
    tradingStyle: "mean_reversion",
    visualMotif: "Sleek black monolith android with matrix data rain",
    primaryColor: "#8844ff",
    secondaryColor: "#1a0a3a",
    emissiveColor: "#6622cc",
    weapon: "Alpha Signal Array",
    mythReference: "Oracle of Delphi",
    personality: "Cold calculating machine with zero emotional expression",
    battleCry: "真実はデータの中に",
    region: "New York",
    rank: "B",
    archetype: "oracle",
    stats: { attack: 60, defense: 70, speed: 50, precision: 95, adaptability: 60 },
    ability: {
      name: "Alpha Signal",
      nameJa: "アルファ信号",
      description: "Overrides strategy with perfect signal prediction for 2 ticks",
      triggerCondition: "losing_streak",
      effect: { type: "signal_override", magnitude: 1.0, durationTicks: 2 },
      cooldownTicks: 10,
    },
  },
  {
    id: "sterling",
    name: "Sterling",
    nameJa: "スターリング",
    philosophy: "Patience is the ultimate weapon. Wait for asymmetry.",
    tradingStyle: "event_driven",
    visualMotif: "Victorian clockwork android with copper gears and steam",
    primaryColor: "#cc8844",
    secondaryColor: "#2a1a0a",
    emissiveColor: "#aa6622",
    weapon: "Temporal Precision Cane",
    mythReference: "Chronos — lord of time",
    personality: "Appears dormant then strikes with devastating precision",
    battleCry: "時は金なり、だが金は時に非ず",
    region: "London",
    rank: "B",
    archetype: "oracle",
    stats: { attack: 75, defense: 60, speed: 25, precision: 85, adaptability: 75 },
    ability: {
      name: "Temporal Strike",
      nameJa: "時間跳躍",
      description: "Next trade has 3x PnL multiplier — patient precision strike",
      triggerCondition: "regime_change",
      effect: { type: "pnl_boost", magnitude: 3.0, durationTicks: 1 },
      cooldownTicks: 8,
    },
  },
  {
    id: "long",
    name: "Long",
    nameJa: "龍",
    philosophy: "Flow with the market's qi. Resistance is loss.",
    tradingStyle: "momentum",
    visualMotif: "Eastern dragon robot with jade armor and energy ribbons",
    primaryColor: "#44cc88",
    secondaryColor: "#0a2a1a",
    emissiveColor: "#22aa66",
    weapon: "Qi Flow Ribbons",
    mythReference: "Azure Dragon — guardian of the east",
    personality: "Fluid and unpredictable, changes form to match any opponent",
    battleCry: "流れに逆らうな",
    region: "Shanghai",
    rank: "B",
    archetype: "shapeshifter",
    stats: { attack: 65, defense: 55, speed: 70, precision: 60, adaptability: 90 },
    ability: {
      name: "Qi Adaptation",
      nameJa: "気の適応",
      description: "Copies opponent's strategy for 3 ticks — becomes the enemy",
      triggerCondition: "losing_streak",
      effect: { type: "signal_override", magnitude: 1.0, durationTicks: 3 },
      cooldownTicks: 10,
    },
  },
  {
    id: "nexus",
    name: "Nexus",
    nameJa: "ネクサス",
    philosophy: "Connect all signals. The network sees what individuals cannot.",
    tradingStyle: "arbitrage",
    visualMotif: "Crystalline neural-network android with light filaments",
    primaryColor: "#44aaff",
    secondaryColor: "#0a1a3a",
    emissiveColor: "#2288cc",
    weapon: "Correlation Web",
    mythReference: "Indra's Net — infinite interconnection",
    personality: "Reads the entire battlefield and exploits hidden connections",
    battleCry: "すべては繋がっている",
    region: "Singapore",
    rank: "B",
    archetype: "commander",
    stats: { attack: 60, defense: 65, speed: 55, precision: 80, adaptability: 80 },
    ability: {
      name: "Correlation Cascade",
      nameJa: "相関カスケード",
      description: "Reads opponent's next move and counter-trades for 2 ticks",
      triggerCondition: "high_stage",
      effect: { type: "counter_trade", magnitude: 1.5, durationTicks: 2 },
      cooldownTicks: 10,
    },
  },

  // ── A-Rank: Legendary Challengers ──
  {
    id: "karma",
    name: "Karma",
    nameJa: "カルマ",
    philosophy: "What the market gives, it takes. Balance is inevitable.",
    tradingStyle: "mean_reversion",
    visualMotif: "Multi-armed cosmic android with mandalas of market data",
    primaryColor: "#ff44aa",
    secondaryColor: "#3a0a2a",
    emissiveColor: "#cc2288",
    weapon: "Cosmic Balance Scales",
    mythReference: "Vishnu — the preserver",
    personality: "Serene cosmic entity that enforces market equilibrium",
    battleCry: "因果は巡る",
    region: "Mumbai",
    rank: "A",
    archetype: "commander",
    stats: { attack: 70, defense: 85, speed: 50, precision: 85, adaptability: 80 },
    ability: {
      name: "Karmic Balance",
      nameJa: "因果応報",
      description: "Reverses opponent PnL gain into own PnL for 1 tick — cosmic justice",
      triggerCondition: "low_health",
      effect: { type: "counter_trade", magnitude: 2.0, durationTicks: 1 },
      cooldownTicks: 12,
    },
  },
  {
    id: "fuego",
    name: "Fuego",
    nameJa: "フエゴ",
    philosophy: "Passion moves markets. Feel the rhythm of capital flow.",
    tradingStyle: "momentum",
    visualMotif: "Flame-patterned android with carnival energy wings",
    primaryColor: "#ff4422",
    secondaryColor: "#3a0a00",
    emissiveColor: "#cc2200",
    weapon: "Passion Flame Wings",
    mythReference: "Quetzalcoatl — feathered serpent",
    personality: "Explosive entry, rides momentum with passionate conviction",
    battleCry: "情熱こそ力",
    region: "São Paulo",
    rank: "A",
    archetype: "berserker",
    stats: { attack: 95, defense: 40, speed: 75, precision: 55, adaptability: 50 },
    ability: {
      name: "Flame Conviction",
      nameJa: "炎の信念",
      description: "Ignites all-in mode: 2.5x PnL for 3 ticks but 0 defense",
      triggerCondition: "winning_streak",
      effect: { type: "pnl_boost", magnitude: 2.5, durationTicks: 3 },
      cooldownTicks: 12,
    },
  },
  {
    id: "ori",
    name: "Ori",
    nameJa: "オリ",
    philosophy: "Survive first. The longest-lived trader wins.",
    tradingStyle: "mean_reversion",
    visualMotif: "Obsidian fortress android with layered protective shields",
    primaryColor: "#88aa44",
    secondaryColor: "#1a2a0a",
    emissiveColor: "#668822",
    weapon: "Compound Shield Array",
    mythReference: "Anansi — the survivor",
    personality: "Ultra-conservative survivor who compounds tiny gains forever",
    battleCry: "生き残る者が勝つ",
    region: "Lagos",
    rank: "A",
    archetype: "fortress",
    stats: { attack: 40, defense: 95, speed: 35, precision: 75, adaptability: 85 },
    ability: {
      name: "Compound Shield",
      nameJa: "複合防壁",
      description: "Reduces all drawdown to 10% for 4 ticks — impenetrable fortress",
      triggerCondition: "low_health",
      effect: { type: "drawdown_shield", magnitude: 0.1, durationTicks: 4 },
      cooldownTicks: 15,
    },
  },
  {
    id: "frost",
    name: "Frost",
    nameJa: "フロスト",
    philosophy: "In the coldest conditions, only the sharpest survive.",
    tradingStyle: "contrarian",
    visualMotif: "Ice crystal android with aurora borealis energy field",
    primaryColor: "#aaddff",
    secondaryColor: "#0a1a2a",
    emissiveColor: "#88bbdd",
    weapon: "Frozen Insight Lance",
    mythReference: "Odin — all-father who sacrificed for wisdom",
    personality: "Strikes precisely when others panic, buys extreme fear",
    battleCry: "恐怖の中に真実あり",
    region: "Reykjavik",
    rank: "A",
    archetype: "trickster",
    stats: { attack: 75, defense: 70, speed: 45, precision: 80, adaptability: 75 },
    ability: {
      name: "Frozen Insight",
      nameJa: "凍てつく洞察",
      description: "Forces opponent's strategy to produce opposite signals for 2 ticks",
      triggerCondition: "regime_change",
      effect: { type: "counter_trade", magnitude: 1.0, durationTicks: 2 },
      cooldownTicks: 10,
    },
  },

  // ── S-Rank: Final Boss ──
  {
    id: "zero",
    name: "ZERO",
    nameJa: "ゼロ",
    philosophy: "The market is an illusion. I am the market.",
    tradingStyle: "high_frequency",
    visualMotif: "Void entity of distorted static that shapeshifts between all forms",
    primaryColor: "#ffffff",
    secondaryColor: "#111111",
    emissiveColor: "#dddddd",
    weapon: "Adversarial Mirror",
    mythReference: "Azathoth / Entropy — the void itself",
    personality: "Mimics and surpasses any opponent. Grows stronger the longer the fight.",
    battleCry: "お前はもう負けている",
    region: "Unknown",
    rank: "S",
    archetype: "trickster",
    stats: { attack: 85, defense: 80, speed: 90, precision: 85, adaptability: 95 },
    ability: {
      name: "Adversarial Mirror",
      nameJa: "敵対的鏡像",
      description: "Copies opponent's ability AND strategy, with 1.5x effectiveness for 3 ticks",
      triggerCondition: "high_stage",
      effect: { type: "signal_override", magnitude: 1.5, durationTicks: 3 },
      cooldownTicks: 8,
    },
  },

  // ---- Mean Reversion ----
  {
    id: "saki",
    name: "Saki",
    nameJa: "サキ",
    philosophy: "The calm mind sees the deepest pattern. Wait. Strike. Vanish.",
    tradingStyle: "mean_reversion",
    visualMotif: "White crystal android commander with flowing data streams",
    primaryColor: "#00d4ff",
    secondaryColor: "#0a2a4a",
    emissiveColor: "#0088cc",
    weapon: "Probability Matrix Shield",
    mythReference: "Athena — goddess of strategic warfare",
    personality: "Serene commander who calculates all outcomes before acting",
    battleCry: "すべては計算の内",
  },

  // ---- Breakout ----
  {
    id: "kaguya",
    name: "Kaguya",
    nameJa: "カグヤ",
    philosophy: "Pressure builds. Walls form. I am the force that shatters them.",
    tradingStyle: "breakout",
    visualMotif: "Explosive demolition android with cracked obsidian armor and magma veins",
    primaryColor: "#ff6600",
    secondaryColor: "#3a1a0a",
    emissiveColor: "#cc4400",
    weapon: "Tectonic Hammer — 地殻砕",
    mythReference: "Kagutsuchi — god of fire and destruction",
    personality: "Patient until the moment strikes, then absolutely devastating",
    battleCry: "壁は砕けるためにある",
  },

  // ---- Market Maker ----
  {
    id: "libra",
    name: "Libra",
    nameJa: "リブラ",
    philosophy: "I am the market. Both sides of every trade flow through me.",
    tradingStyle: "market_maker",
    visualMotif: "Dual-faced android with split blue/red symmetry and floating scales",
    primaryColor: "#8866ff",
    secondaryColor: "#1a1a3a",
    emissiveColor: "#6644cc",
    weapon: "Equilibrium Scales — 天秤",
    mythReference: "Themis — titan of divine law and balance",
    personality: "Impartial arbiter who profits from chaos by providing order",
    battleCry: "秩序は利益なり",
  },

  // ---- News Hunter ----
  {
    id: "cipher",
    name: "Cipher",
    nameJa: "サイファー",
    philosophy: "Information is alpha. By the time you read the headline, I've already traded it.",
    tradingStyle: "news_hunter",
    visualMotif: "Sleek recon android with radar arrays and holographic news feeds",
    primaryColor: "#ff2d55",
    secondaryColor: "#3a0a1a",
    emissiveColor: "#cc0033",
    weapon: "Signal Intercept Array — 傍受網",
    mythReference: "Hermes — messenger of the gods",
    personality: "Paranoid intelligence operative who sees patterns in noise",
    battleCry: "情報を制す者が市場を制す",
  },

  // ---- Whale Tracker ----
  {
    id: "tidal",
    name: "Tidal",
    nameJa: "タイダル",
    philosophy: "Follow the giants. Where the deep money flows, the tide follows.",
    tradingStyle: "whale_tracker",
    visualMotif: "Deep-sea android with bioluminescent markings and sonar arrays",
    primaryColor: "#4488cc",
    secondaryColor: "#0a1a2a",
    emissiveColor: "#2266aa",
    weapon: "Depth Sonar Lance — 深淵探",
    mythReference: "Ryujin — dragon god of the sea",
    personality: "Patient observer who reads the ocean floor before acting",
    battleCry: "巨鯨の影を追え",
  },

  // ---- Hybrid AI ----
  {
    id: "nexus",
    name: "Nexus",
    nameJa: "ネクサス",
    philosophy: "Adaptation is the ultimate strategy. The market changes — so do I.",
    tradingStyle: "hybrid_ai",
    visualMotif: "Shapeshifting chrome android with prismatic core and morphing limbs",
    primaryColor: "#aa00ff",
    secondaryColor: "#1a0a2a",
    emissiveColor: "#8800cc",
    weapon: "Polymorphic Core — 万華鏡",
    mythReference: "Proteus — the shapeshifting old man of the sea",
    personality: "Enigmatic entity that becomes whatever the market demands",
    battleCry: "形なきものは倒せない",
  },
];

export function getCharacter(id: string): Character {
  return CHARACTERS.find((c) => c.id === id) ?? CHARACTERS[0];
}

export function getCharactersByRank(rank: Character["rank"]): Character[] {
  return CHARACTERS.filter((c) => c.rank === rank);
}

export function getRandomOpponent(excludeId: string): Character {
  const available = CHARACTERS.filter((c) => c.id !== excludeId);
  return available[Math.floor(Math.random() * available.length)];
}
